# Generated by Django 6.0.2 on 2026-04-22 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la zone')),
                ('type', models.CharField(choices=[('pollution', 'Zone de Pollution'), ('industrial', 'Zone Industrielle'), ('administrative', 'Zone Administrative')], default='administrative', max_length=20, verbose_name='Type de zone')),
                ('geojson', models.JSONField(help_text='Polygon GeoJSON geometry. Example: {"type": "Polygon", "coordinates": [[[lng, lat], ...]]}', verbose_name='Géométrie GeoJSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollution_level', models.FloatField(blank=True, null=True, verbose_name='Niveau de pollution (µg/m³)')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Population estimée')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='gis_analytics.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Source de Données Zone',
                'verbose_name_plural': 'Sources de Données Zones',
                'ordering': ['-year'],
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['type'], name='zone_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zonedatasource',
            unique_together={('zone', 'year')},
        ),
    ]
