# Generated by Django 6.0.2 on 2026-04-28 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la couche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#ff0000', max_length=50, verbose_name="Couleur d'affichage")),
                ('regions', models.JSONField(default=list, help_text='Liste des noms de communes/wilayas inclus dans cette couche.', verbose_name='Régions sélectionnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_layers_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par (Architecte)')),
            ],
            options={
                'verbose_name': 'Couche Spatiale (AreaLayer)',
                'verbose_name_plural': 'Couches Spatiales (AreaLayers)',
                'ordering': ['-created_at'],
            },
        ),
    ]
