# Generated by Django 6.0.2 on 2026-05-24 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_analytics', '0002_arealayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='color',
            field=models.CharField(default='#3388ff', max_length=50, verbose_name="Couleur d'affichage"),
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.CharField(choices=[('pollution', 'Zone de Pollution'), ('industrial', 'Zone Industrielle'), ('administrative', 'Zone Administrative'), ('custom', 'Zone Personnalisée')], default='custom', max_length=20, verbose_name='Type de zone'),
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la commune')),
                ('wilaya', models.CharField(blank=True, default='Tlemcen', max_length=255, verbose_name='Wilaya')),
                ('geojson', models.JSONField(help_text='Simplified Polygon GeoJSON bounding the commune area.', verbose_name='Géométrie GeoJSON')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='commune_name_idx')],
            },
        ),
    ]
