# Generated by Django 6.0.2 on 2026-05-24 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_analytics', '0003_zone_color_zone_description_alter_zone_type_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='geojson',
            field=models.JSONField(blank=True, default=None, help_text='Polygon GeoJSON geometry. Use ZoneGeometry instead for multi-polygon zones.', null=True, verbose_name='Géométrie GeoJSON (dépréciée)'),
        ),
        migrations.CreateModel(
            name='ZoneGeometry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry_type', models.CharField(default='Polygon', help_text='Polygon | Rectangle | Circle', max_length=20, verbose_name='Type de géométrie')),
                ('geometry', models.JSONField(help_text='GeoJSON geometry object. Example: {"type": "Polygon", "coordinates": [[[lng,lat],...]]}', verbose_name='Géométrie GeoJSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='gis_analytics.zone', verbose_name='Zone parente')),
            ],
            options={
                'verbose_name': 'Géométrie de Zone',
                'verbose_name_plural': 'Géométries de Zones',
                'ordering': ['created_at'],
            },
        ),
    ]
