# Generated by Django 6.0.2 on 2026-03-08 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_alter_patient_adresse_alter_patient_sexe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerCase',
            fields=[
                ('id_cancer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taille_cancer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taille du cancer')),
                ('type_cancer', models.CharField(max_length=200, verbose_name='Type de cancer')),
                ('sous_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sous-type')),
                ('niveau', models.CharField(blank=True, max_length=100, null=True, verbose_name='Niveau')),
                ('etat', models.CharField(blank=True, max_length=100, null=True, verbose_name='État')),
                ('classification_stade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classification stade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_cases', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Cas de Cancer',
                'verbose_name_plural': 'Cas de Cancers',
            },
        ),
        migrations.CreateModel(
            name='Anapath',
            fields=[
                ('id_anapath', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('N_dossier_anapath', models.CharField(max_length=100, verbose_name='N° Dossier Anapath')),
                ('N_lecture', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Lecture')),
                ('medecin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Médecin')),
                ('date_etude', models.DateField(blank=True, null=True, verbose_name="Date d'étude")),
                ('cancer_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anapath', to='cancers.cancercase', verbose_name='Cas de Cancer')),
            ],
            options={
                'verbose_name': 'Donnée Anapath',
                'verbose_name_plural': 'Données Anapaths',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id_analyse', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_analyse', models.CharField(max_length=200, verbose_name="Type d'analyse")),
                ('date_analyse', models.DateField(blank=True, null=True, verbose_name="Date d'analyse")),
                ('document', models.FileField(blank=True, null=True, upload_to='analyses/documents/', verbose_name='Document')),
                ('cancer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cancers.cancercase', verbose_name='Cas de Cancer')),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='Imaging',
            fields=[
                ('id_imagerie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_imagerie', models.CharField(max_length=200, verbose_name="Type d'imagerie")),
                ('date_imagerie', models.DateField(blank=True, null=True, verbose_name="Date d'imagerie")),
                ('cancer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagings', to='cancers.cancercase', verbose_name='Cas de Cancer')),
            ],
            options={
                'verbose_name': 'Imagerie',
                'verbose_name_plural': 'Imageries',
            },
        ),
    ]
