# Generated by Django 6.0.2 on 2026-03-10 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id_type', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du type de cancer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Cancer',
                'verbose_name_plural': 'Types de Cancer',
            },
        ),
        migrations.AddField(
            model_name='cancercase',
            name='dynamic_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Attributs dynamiques'),
        ),
        migrations.AlterField(
            model_name='cancercase',
            name='type_cancer',
            field=models.CharField(max_length=200, verbose_name='Type de cancer (Ancien)'),
        ),
        migrations.CreateModel(
            name='CancerAttribute',
            fields=[
                ('id_attribute', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_interne', models.CharField(help_text="Ex: 'taille_tumeur'", max_length=100)),
                ('label', models.CharField(help_text="Ex: 'Taille de la tumeur (cm)'", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('date', 'Date'), ('boolean', 'Booléen (Oui/Non)'), ('select', 'Liste de choix')], default='text', max_length=20)),
                ('requis', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, help_text='Liste des options pour \'select\', ex: ["Option 1", "Option 2"]', null=True)),
                ('is_basic', models.BooleanField(default=False, help_text='Si coché, cet attribut apparaît pour TOUS les cancers.')),
                ('cancer_type', models.ForeignKey(blank=True, help_text='Si vide, cet attribut est considéré comme basique (pour tous les types).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cancers.cancertype', verbose_name='Type de Cancer')),
            ],
            options={
                'verbose_name': 'Attribut de Cancer',
                'verbose_name_plural': 'Attributs de Cancer',
            },
        ),
        migrations.AddField(
            model_name='cancercase',
            name='cancer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cancers.cancertype', verbose_name='Type de Cancer'),
        ),
    ]
