# Generated by Django 6.0.2 on 2026-03-10 01:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0002_cancertype_cancercase_dynamic_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerTreatment',
            fields=[
                ('id_traitement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_traitement', models.CharField(max_length=200, verbose_name='Type de traitement')),
                ('date_traitement', models.DateField(blank=True, null=True, verbose_name='Date du traitement')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques/Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='cancers.cancercase', verbose_name='Cas de Cancer')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['-date_traitement'],
            },
        ),
    ]
