# Generated by Django 6.0.2 on 2026-03-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0003_cancertreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='imaging',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='imaging/documents/', verbose_name='Document'),
        ),
    ]
