# Generated by Django 6.0.2 on 2026-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0004_imaging_document'),
        ('patients', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cancercase',
            index=models.Index(fields=['etat'], name='cancer_etat_idx'),
        ),
        migrations.AddIndex(
            model_name='cancercase',
            index=models.Index(fields=['type_cancer'], name='cancer_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cancercase',
            index=models.Index(fields=['created_at'], name='cancer_created_at_idx'),
        ),
    ]
