# Generated by Django 6.0.2 on 2026-03-13 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingType',
            fields=[
                ('id_imaging_type', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name="Nom du type d'imagerie")),
            ],
            options={
                'verbose_name': "Type d'Imagerie",
                'verbose_name_plural': "Types d'Imagerie",
            },
        ),
        migrations.AddField(
            model_name='cancerattribute',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Permet d'activer/désactiver ce champ dans le formulaire.", verbose_name='Actif'),
        ),
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id_analysis_type', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name="Nom du type d'analyse")),
                ('cancer_type', models.ForeignKey(blank=True, help_text="Si vide, ce type d'analyse est disponible pour tous les cancers.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_types', to='cancers.cancertype', verbose_name='Type de Cancer')),
            ],
            options={
                'verbose_name': "Type d'Analyse",
                'verbose_name_plural': "Types d'Analyse",
                'unique_together': {('nom', 'cancer_type')},
            },
        ),
    ]
