# Generated by Django 6.0.2 on 2026-03-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0006_imagingtype_cancerattribute_is_active_analysistype'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingtype',
            name='cancer_type',
            field=models.ForeignKey(blank=True, help_text="Si vide, ce type d'imagerie est disponible pour tous les cancers.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_types', to='cancers.cancertype', verbose_name='Type de Cancer'),
        ),
        migrations.AlterField(
            model_name='cancercase',
            name='type_cancer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type de cancer (Ancien)'),
        ),
        migrations.AlterField(
            model_name='imagingtype',
            name='nom',
            field=models.CharField(max_length=200, verbose_name="Nom du type d'imagerie"),
        ),
        migrations.AlterUniqueTogether(
            name='imagingtype',
            unique_together={('nom', 'cancer_type')},
        ),
    ]
