# Generated by Django 6.0.2 on 2026-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0007_imagingtype_cancer_type_alter_cancercase_type_cancer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancercase',
            name='classification_stade',
        ),
        migrations.AddField(
            model_name='anapath',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='Compte-rendu'),
        ),
        migrations.AlterField(
            model_name='cancerattribute',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='cancercase',
            name='dynamic_attributes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Attributs Dynamiques'),
        ),
        migrations.AlterField(
            model_name='cancercase',
            name='etat',
            field=models.CharField(default='en_attente', max_length=50, verbose_name='État du dossier'),
        ),
    ]
