# Generated by Django 6.0.2 on 2026-04-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0008_remove_cancercase_classification_stade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancerattribute',
            options={'ordering': ['label'], 'verbose_name': 'Attribut de Cancer', 'verbose_name_plural': 'Attributs de Cancer'},
        ),
        migrations.AddField(
            model_name='cancercase',
            name='date_diagnostic',
            field=models.DateField(blank=True, null=True, verbose_name='Date du diagnostic'),
        ),
    ]
