# Generated by Django 6.0.2 on 2026-05-23 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancers', '0009_alter_cancerattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id_followup', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(verbose_name='Date de visite')),
                ('visit_type', models.CharField(max_length=200, verbose_name='Type de visite')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Constatations')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='Prochaine visite')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='cancers.cancercase', verbose_name='Cas de Cancer')),
            ],
            options={
                'verbose_name': 'Suivi',
                'verbose_name_plural': 'Suivis',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MolecularMarker',
            fields=[
                ('id_molecular', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marker_name', models.CharField(max_length=200, verbose_name='Nom du marqueur')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Résultat')),
                ('method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Méthode')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Date du test')),
                ('laboratory', models.CharField(blank=True, max_length=200, null=True, verbose_name='Laboratoire')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecular_markers', to='cancers.cancercase', verbose_name='Cas de Cancer')),
            ],
            options={
                'verbose_name': 'Marqueur Moléculaire',
                'verbose_name_plural': 'Marqueurs Moléculaires',
                'ordering': ['-test_date'],
            },
        ),
    ]
