# Generated by Django 6.0.2 on 2026-05-24 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_patient', 'Création patient'), ('update_patient', 'Modification patient'), ('delete_patient', 'Suppression patient'), ('duplicate_patient', 'Fusion doublon patient'), ('create_case', 'Création cas cancer'), ('update_case', 'Modification cas cancer'), ('delete_case', 'Suppression cas cancer'), ('upload_document', 'Upload document'), ('delete_document', 'Suppression document'), ('preview_document', 'Prévisualisation document'), ('download_document', 'Téléchargement document'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('failed_login', 'Échec connexion'), ('add_followup', 'Ajout suivi'), ('modify_followup', 'Modification suivi'), ('add_treatment', 'Ajout traitement'), ('update_treatment', 'Modification traitement'), ('create_user', 'Création utilisateur'), ('update_user', 'Modification utilisateur'), ('delete_user', 'Suppression utilisateur')], db_index=True, max_length=50, verbose_name="Type d'action")),
                ('entity_type', models.CharField(choices=[('patient', 'Patient'), ('cancer_case', 'Cas cancer'), ('document', 'Document'), ('user', 'Utilisateur'), ('followup', 'Suivi'), ('treatment', 'Traitement'), ('system', 'Système')], db_index=True, max_length=50, verbose_name="Type d'entité")),
                ('entity_id', models.CharField(blank=True, max_length=255, verbose_name="ID de l'entité")),
                ('entity_label', models.CharField(blank=True, max_length=500, verbose_name="Libellé de l'entité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('route_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin de la requête')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='audit_audit_action__eafc67_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx')],
            },
        ),
    ]
