# Generated by Django 6.0.2 on 2026-04-28 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancers', '0009_alter_cancerattribute_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RcpCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('discussed', 'Discuté'), ('deferred', 'Reporté')], default='pending', max_length=50)),
                ('duration', models.IntegerField(default=15, help_text='Planned duration in minutes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancers.cancercase')),
                ('presenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RcpSession',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('isOnline', models.BooleanField(default=False)),
                ('meetingLink', models.URLField(blank=True, null=True)),
                ('service', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_rcps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='RcpProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('final', 'Final'), ('signed', 'Signé')], default='draft', max_length=50)),
                ('signedAt', models.DateTimeField(blank=True, null=True)),
                ('fileUrl', models.FileField(blank=True, null=True, upload_to='rcp_protocols/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_protocols', to=settings.AUTH_USER_MODEL)),
                ('signedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_protocols', to=settings.AUTH_USER_MODEL)),
                ('rcp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='rcp.rcpsession')),
            ],
        ),
        migrations.CreateModel(
            name='RcpMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(default='text', max_length=50)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('reactions', models.JSONField(blank=True, default=list)),
                ('isEdited', models.BooleanField(default=False)),
                ('isPinned', models.BooleanField(default=False)),
                ('readBy', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rcp_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rcp.rcpcase')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rcp.rcpsession')),
            ],
        ),
        migrations.CreateModel(
            name='RcpDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.TextField()),
                ('decisionType', models.CharField(max_length=100)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('followUp', models.TextField(blank=True, null=True)),
                ('followUpDate', models.DateField(blank=True, null=True)),
                ('validatedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('implemented', 'Appliquée'), ('cancelled', 'Annulée')], default='draft', max_length=50)),
                ('implementedAt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rcp_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='rcp.rcpcase')),
                ('validatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_decisions', to=settings.AUTH_USER_MODEL)),
                ('rcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='rcp.rcpsession')),
            ],
        ),
        migrations.AddField(
            model_name='rcpcase',
            name='rcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='rcp.rcpsession'),
        ),
        migrations.CreateModel(
            name='RcpTemplate',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sections', models.JSONField(default=list)),
                ('isDefault', models.BooleanField(default=False)),
                ('usageCount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RcpParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', 'Coordinateur'), ('presenter', 'Présentateur'), ('member', 'Membre'), ('invited', 'Invité')], max_length=50)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('pending', 'En attente'), ('declined', 'Décliné'), ('absent', 'Absent')], default='pending', max_length=50)),
                ('isRequired', models.BooleanField(default=True)),
                ('invitedAt', models.DateTimeField(auto_now_add=True)),
                ('respondedAt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rcp.rcpsession')),
            ],
            options={
                'unique_together': {('rcp', 'user')},
            },
        ),
    ]
