# Generated by Django 6.0.2 on 2026-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcpsession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rcpsession',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='rcpsession',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
