# Generated by Django 6.0.2 on 2026-05-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0002_alter_rcpsession_date_alter_rcpsession_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcpsession',
            name='isAllDoctors',
            field=models.BooleanField(default=False, help_text='If True, all doctors can access this RCP'),
        ),
        migrations.AddField(
            model_name='rcpsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rcpsession',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
