# Generated by Django 6.0.2 on 2026-05-24 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0003_rcpsession_isalldoctors_rcpsession_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RcpNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_message', 'Nouveau message'), ('participant_added', 'Participant ajouté'), ('case_added', 'Cas ajouté'), ('status_changed', 'Changement de statut'), ('report_generated', 'Compte-rendu généré'), ('report_signed', 'Compte-rendu signé')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rcp.rcpsession')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcp_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
