# Generated by Django 6.0.2 on 2026-03-06 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_malade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('N_carte_nationale', models.CharField(blank=True, max_length=50, null=True)),
                ('N_securite_sociale', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('situation_familiale', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)')], max_length=20)),
                ('nb_enfants', models.PositiveIntegerField(default=0)),
                ('group_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kg', max_digits=5, null=True)),
                ('taille', models.PositiveIntegerField(blank=True, help_text='Taille en cm', null=True)),
                ('autre_maladie', models.TextField(blank=True, null=True)),
                ('nb_fois_cancer', models.PositiveIntegerField(default=0)),
                ('deces', models.BooleanField(default=False)),
                ('cause', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
