# Generated by Django 6.0.2 on 2026-03-09 22:32

import django.db.models.deletion
import patients.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_adresse_alter_patient_sexe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHabitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_reponse', models.CharField(choices=[('booleen', 'Booléen (Oui/Non)'), ('texte', 'Texte libre'), ('nombre', 'Nombre'), ('choix_multiple', 'Choix Multiple')], default='booleen', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='Liste des options pour choix multiple, ex: ["Jamais", "Parfois"]', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Question Habitude de Vie',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AntecedentFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie_parent', models.CharField(max_length=255)),
                ('age_parent', models.PositiveIntegerField(blank=True, null=True)),
                ('parent_decede', models.BooleanField(default=False)),
                ('cancer_parent', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents_familiaux', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Antécédent Familial',
                'verbose_name_plural': 'Antécédents Familiaux',
            },
        ),
        migrations.CreateModel(
            name='PatientOnboardingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=patients.models.default_expiration)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_token', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseHabitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.JSONField(blank=True, help_text='La valeur de la réponse formatée en JSON', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitudes_reponses', to='patients.patient')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.questionhabitude')),
            ],
            options={
                'unique_together': {('patient', 'question')},
            },
        ),
    ]
