# Generated by Django 6.0.2 on 2026-03-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_questionhabitude_antecedentfamilial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='habitudes_fixes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
