# Generated by Django 6.0.2 on 2026-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_habitudes_fixes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nom'], name='patient_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['prenom'], name='patient_prenom_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_naissance'], name='patient_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['sexe'], name='patient_sexe_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['deces'], name='patient_deces_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nom', 'prenom'], name='patient_full_name_idx'),
        ),
    ]
