# Generated by Django 6.0.2 on 2026-04-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['latitude', 'longitude'], name='patient_coords_idx'),
        ),
    ]
